### ISSUE TITLE
есть проблемы...

### ISSUE THREAD

**Issue by Roman-code37** [Roman-code37/07.webapp#1]
@coursar
1.не получается настроить Travis-ci,при сборке пишет вот это -
The command "rake" exited with 1.
Done. Your build exited with 1.
и статус Travis-ci - failing
2.когда запускаешь проект, то компилятор выдает - Error:java: invalid source release: 11

**Comment by coursar** [comment]
1. Внимательно пересмотрите видео: вам нужно сначала создать свой проект на Heroku и потом его название вписать в .travis.yml (вы же пытаетесь публиковать в проект itpark-webapp, который вам не принадлежит, либо вы неправильно указали Token):
`Message: You do not have access to the app itpark-webapp.`
2. Если вы делали по видео и там Java 11, то вы должны выбирать Java 11 на компьютере, а не Java 8.
